# Generated by Django 4.2 on 2023-06-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_book_cover_book_samples'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='samples',
            new_name='sample',
        ),
    ]
